//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/auth.proto
// Note: requires additional types generated from: ProtoFiles/common.proto
// Note: requires additional types generated from: ProtoFiles/profile.proto
namespace proto_auth
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Auth")]
  public partial class Auth : global::ProtoBuf.IExtensible
  {
    public Auth() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private proto_auth.Auth.AuthType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_auth.Auth.AuthType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private proto_auth.Auth.Request.OAuth _m_oauth = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"m_oauth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_auth.Auth.Request.OAuth m_oauth
    {
      get { return _m_oauth; }
      set { _m_oauth = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OAuth")]
  public partial class OAuth : global::ProtoBuf.IExtensible
  {
    public OAuth() {}
    
    private string _access_token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string access_token
    {
      get { return _access_token; }
      set { _access_token = value; }
    }
    private string _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private proto_auth.Auth.OAuthProvider _provider;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"provider", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_auth.Auth.OAuthProvider provider
    {
      get { return _provider; }
      set { _provider = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private proto_profile.UserInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto_profile.UserInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"AuthType")]
    public enum AuthType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OAuth", Value=2)]
      OAuth = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OAuthProvider")]
    public enum OAuthProvider
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"VK", Value=0)]
      VK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FB", Value=1)]
      FB = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}