//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/game.proto
// Note: requires additional types generated from: ProtoFiles/common.proto
// Note: requires additional types generated from: ProtoFiles/profile.proto
namespace proto_game
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatValue")]
  public partial class StatValue : global::ProtoBuf.IExtensible
  {
    public StatValue() {}
    
    private proto_game.Stats _stat;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Stats stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
    private float _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float value
    {
      get { return _value; }
      set { _value = value; }
    }
    private float _step;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float step
    {
      get { return _step; }
      set { _step = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector")]
  public partial class Vector : global::ProtoBuf.IExtensible
  {
    public Vector() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ping")]
  public partial class Ping : global::ProtoBuf.IExtensible
  {
    public Ping() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInput")]
  public partial class PlayerInput : global::ProtoBuf.IExtensible
  {
    public PlayerInput() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private float _force_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"force_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float force_x
    {
      get { return _force_x; }
      set { _force_x = value; }
    }
    private float _force_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"force_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float force_y
    {
      get { return _force_y; }
      set { _force_y = value; }
    }
    private float _rotation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private int _tick;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private proto_game.Shoot _shoot = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"shoot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_game.Shoot shoot
    {
      get { return _shoot; }
      set { _shoot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _force_x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"force_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float force_x
    {
      get { return _force_x; }
      set { _force_x = value; }
    }
    private float _force_y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"force_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float force_y
    {
      get { return _force_y; }
      set { _force_y = value; }
    }
    private int _tick;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private proto_game.Shoot _shoot = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"shoot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_game.Shoot shoot
    {
      get { return _shoot; }
      set { _shoot = value; }
    }
    private long _time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FindRoom")]
  public partial class FindRoom : global::ProtoBuf.IExtensible
  {
    public FindRoom() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinGame")]
  public partial class JoinGame : global::ProtoBuf.IExtensible
  {
    public JoinGame() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private proto_profile.PlayerClasses _class;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_profile.PlayerClasses @class
    {
      get { return _class; }
      set { _class = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private int _time_left;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time_left", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time_left
    {
      get { return _time_left; }
      set { _time_left = value; }
    }
    private readonly global::System.Collections.Generic.List<float> _outer_border = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(2, Name=@"outer_border", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> outer_border
    {
      get { return _outer_border; }
    }
  
    private int _tick;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatUpgrade")]
  public partial class StatUpgrade : global::ProtoBuf.IExtensible
  {
    public StatUpgrade() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private proto_game.Stats _stat;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Stats stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerUpgrade")]
  public partial class PlayerUpgrade : global::ProtoBuf.IExtensible
  {
    public PlayerUpgrade() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrabPowerUp")]
  public partial class GrabPowerUp : global::ProtoBuf.IExtensible
  {
    public GrabPowerUp() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private int _powerUp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"powerUp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int powerUp
    {
      get { return _powerUp; }
      set { _powerUp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrabGoldCoin")]
  public partial class GrabGoldCoin : global::ProtoBuf.IExtensible
  {
    public GrabGoldCoin() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private int _goldCoin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"goldCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goldCoin
    {
      get { return _goldCoin; }
      set { _goldCoin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CastSkill")]
  public partial class CastSkill : global::ProtoBuf.IExtensible
  {
    public CastSkill() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private float _direction;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Shoot")]
  public partial class Shoot : global::ProtoBuf.IExtensible
  {
    public Shoot() {}
    
    private float _direction;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BulletAppeared")]
  public partial class BulletAppeared : global::ProtoBuf.IExtensible
  {
    public BulletAppeared() {}
    
    private int _tick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private float _direction;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MobAppeared")]
  public partial class MobAppeared : global::ProtoBuf.IExtensible
  {
    public MobAppeared() {}
    
    private proto_game.MobType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.MobType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private float _max_hp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"max_hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float max_hp
    {
      get { return _max_hp; }
      set { _max_hp = value; }
    }
    private float _attack_range;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"attack_range", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float attack_range
    {
      get { return _attack_range; }
      set { _attack_range = value; }
    }
    private proto_game.Weapons _weapon_used;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"weapon_used", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Weapons weapon_used
    {
      get { return _weapon_used; }
      set { _weapon_used = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PowerUpAppeared")]
  public partial class PowerUpAppeared : global::ProtoBuf.IExtensible
  {
    public PowerUpAppeared() {}
    
    private proto_game.PowerUpType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.PowerUpType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _lifetime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"lifetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lifetime
    {
      get { return _lifetime; }
      set { _lifetime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PowerUpGrabbed")]
  public partial class PowerUpGrabbed : global::ProtoBuf.IExtensible
  {
    public PowerUpGrabbed() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _who_grabbed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"who_grabbed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int who_grabbed
    {
      get { return _who_grabbed; }
      set { _who_grabbed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerStats")]
  public partial class PlayerStats : global::ProtoBuf.IExtensible
  {
    public PlayerStats() {}
    
    private readonly global::System.Collections.Generic.List<proto_game.StatValue> _stats = new global::System.Collections.Generic.List<proto_game.StatValue>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto_game.StatValue> stats
    {
      get { return _stats; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockAppeared")]
  public partial class BlockAppeared : global::ProtoBuf.IExtensible
  {
    public BlockAppeared() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private proto_game.Vector _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto_game.Vector position
    {
      get { return _position; }
      set { _position = value; }
    }
    private float _hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private proto_game.ExpBlocks _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.ExpBlocks type
    {
      get { return _type; }
      set { _type = value; }
    }
    private float _max_hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"max_hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float max_hp
    {
      get { return _max_hp; }
      set { _max_hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitDie")]
  public partial class UnitDie : global::ProtoBuf.IExtensible
  {
    public UnitDie() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnGoldCoin")]
  public partial class SpawnGoldCoin : global::ProtoBuf.IExtensible
  {
    public SpawnGoldCoin() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitMove")]
  public partial class UnitMove : global::ProtoBuf.IExtensible
  {
    public UnitMove() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private int _tick;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerTurn")]
  public partial class PlayerTurn : global::ProtoBuf.IExtensible
  {
    public PlayerTurn() {}
    
    private float _angle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private int _guid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerExperience")]
  public partial class PlayerExperience : global::ProtoBuf.IExtensible
  {
    public PlayerExperience() {}
    
    private int _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerLevelUp")]
  public partial class PlayerLevelUp : global::ProtoBuf.IExtensible
  {
    public PlayerLevelUp() {}
    
    private int _lvl;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lvl
    {
      get { return _lvl; }
      set { _lvl = value; }
    }
    private int _expLeft;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"expLeft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int expLeft
    {
      get { return _expLeft; }
      set { _expLeft = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerStatusChange")]
  public partial class PlayerStatusChange : global::ProtoBuf.IExtensible
  {
    public PlayerStatusChange() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _hp = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitAttack")]
  public partial class UnitAttack : global::ProtoBuf.IExtensible
  {
    public UnitAttack() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _direction;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerAppeared")]
  public partial class PlayerAppeared : global::ProtoBuf.IExtensible
  {
    public PlayerAppeared() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private proto_game.Vector _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto_game.Vector position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _guid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private proto_game.PlayerStats _stats;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto_game.PlayerStats stats
    {
      get { return _stats; }
      set { _stats = value; }
    }
    private float _hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private bool _local;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"local", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool local
    {
      get { return _local; }
      set { _local = value; }
    }
    private proto_profile.PlayerClasses _class;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_profile.PlayerClasses @class
    {
      get { return _class; }
      set { _class = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private proto_game.Skills _skill;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Skills skill
    {
      get { return _skill; }
      set { _skill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerDisconnected")]
  public partial class PlayerDisconnected : global::ProtoBuf.IExtensible
  {
    public PlayerDisconnected() {}
    
    private int _who;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"who", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int who
    {
      get { return _who; }
      set { _who = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScoreChanged")]
  public partial class ScoreChanged : global::ProtoBuf.IExtensible
  {
    public ScoreChanged() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameFinished")]
  public partial class GameFinished : global::ProtoBuf.IExtensible
  {
    public GameFinished() {}
    
    private int _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _coins;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"coins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coins
    {
      get { return _coins; }
      set { _coins = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DamageDone")]
  public partial class DamageDone : global::ProtoBuf.IExtensible
  {
    public DamageDone() {}
    
    private int _target;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private float _hp_left;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hp_left", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hp_left
    {
      get { return _hp_left; }
      set { _hp_left = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncTick")]
  public partial class SyncTick : global::ProtoBuf.IExtensible
  {
    public SyncTick() {}
    
    private int _tick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillCasted")]
  public partial class SkillCasted : global::ProtoBuf.IExtensible
  {
    public SkillCasted() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _direction;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Weapons")]
    public enum Weapons
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MachineGun", Value=1)]
      MachineGun = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DualMachineGun", Value=2)]
      DualMachineGun = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Canon", Value=3)]
      Canon = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Bullets")]
    public enum Bullets
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Common", Value=1)]
      Common = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MobType")]
    public enum MobType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Basic", Value=1)]
      Basic = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PowerUpType")]
    public enum PowerUpType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DoubleDamage", Value=0)]
      DoubleDamage = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Invisibility", Value=1)]
      Invisibility = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HugeBullets", Value=2)]
      HugeBullets = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Regeneration", Value=3)]
      Regeneration = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Stats")]
    public enum Stats
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MaxHealth", Value=1)]
      MaxHealth = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HealthRegen", Value=2)]
      HealthRegen = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BulletDamage", Value=3)]
      BulletDamage = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillDamage", Value=4)]
      SkillDamage = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MovementSpeed", Value=5)]
      MovementSpeed = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReloadSpeed", Value=6)]
      ReloadSpeed = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Armor", Value=7)]
      Armor = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BulletSpeed", Value=8)]
      BulletSpeed = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillCooldown", Value=9)]
      SkillCooldown = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BulletSize", Value=10)]
      BulletSize = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Skills")]
    public enum Skills
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BigCannon", Value=1)]
      BigCannon = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ExpBlocks")]
    public enum ExpBlocks
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Small", Value=0)]
      Small = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Medium", Value=1)]
      Medium = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Big", Value=2)]
      Big = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Huge", Value=3)]
      Huge = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GoldBlock", Value=4)]
      GoldBlock = 4
    }
  
}