//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/profile.proto
// Note: requires additional types generated from: ProtoFiles/common.proto
namespace proto_profile
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BumpInfo")]
  public partial class BumpInfo : global::ProtoBuf.IExtensible
  {
    public BumpInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _max_value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"max_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_value
    {
      get { return _max_value; }
      set { _max_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClassInfo")]
  public partial class ClassInfo : global::ProtoBuf.IExtensible
  {
    public ClassInfo() {}
    
    private proto_profile.PlayerClasses _class;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_profile.PlayerClasses @class
    {
      get { return _class; }
      set { _class = value; }
    }
    private bool _unlocked;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unlocked", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool unlocked
    {
      get { return _unlocked; }
      set { _unlocked = value; }
    }
    private int _levelRequired;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"levelRequired", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelRequired
    {
      get { return _levelRequired; }
      set { _levelRequired = value; }
    }
    private int _coinsPrice;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"coinsPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coinsPrice
    {
      get { return _coinsPrice; }
      set { _coinsPrice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private int _coins;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"coins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coins
    {
      get { return _coins; }
      set { _coins = value; }
    }
    private readonly global::System.Collections.Generic.List<proto_profile.ClassInfo> _classesInfo = new global::System.Collections.Generic.List<proto_profile.ClassInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"classesInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto_profile.ClassInfo> classesInfo
    {
      get { return _classesInfo; }
    }
  
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeNickname")]
  public partial class ChangeNickname : global::ProtoBuf.IExtensible
  {
    public ChangeNickname() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private bool _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerClasses")]
    public enum PlayerClasses
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Assault", Value=1)]
      Assault = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gunner", Value=2)]
      Gunner = 2
    }
  
}