//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/server.proto
// Note: requires additional types generated from: ProtoFiles/game.proto
namespace proto_server
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private proto_server.Commands _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_server.Commands type
    {
      get { return _type; }
      set { _type = value; }
    }
    private proto_server.RegisterGameNode.Request _register_game_node = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"register_game_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.RegisterGameNode.Request register_game_node
    {
      get { return _register_game_node; }
      set { _register_game_node = value; }
    }
    private proto_server.CreateRemoteGame.Request _create_game_req = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"create_game_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.CreateRemoteGame.Request create_game_req
    {
      get { return _create_game_req; }
      set { _create_game_req = value; }
    }
    private proto_server.PlayersJoin.Request _players_join_req = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"players_join_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.PlayersJoin.Request players_join_req
    {
      get { return _players_join_req; }
      set { _players_join_req = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private proto_server.Commands _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_server.Commands type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _error;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error
    {
      get { return _error; }
      set { _error = value; }
    }
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private proto_server.RegisterGameNode.Response _register_game_node = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"register_game_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.RegisterGameNode.Response register_game_node
    {
      get { return _register_game_node; }
      set { _register_game_node = value; }
    }
    private proto_server.CreateRemoteGame.Response _create_game_res = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"create_game_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.CreateRemoteGame.Response create_game_res
    {
      get { return _create_game_res; }
      set { _create_game_res = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Event")]
  public partial class Event : global::ProtoBuf.IExtensible
  {
    public Event() {}
    
    private proto_server.Events _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_server.Events type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private proto_server.GameNodeStatus _game_node_status = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"game_node_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.GameNodeStatus game_node_status
    {
      get { return _game_node_status; }
      set { _game_node_status = value; }
    }
    private proto_server.GameStatusUpdate _game_status_upd = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"game_status_upd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.GameStatusUpdate game_status_upd
    {
      get { return _game_status_upd; }
      set { _game_status_upd = value; }
    }
    private proto_server.GameFinished _game_finished = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"game_finished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.GameFinished game_finished
    {
      get { return _game_finished; }
      set { _game_finished = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterGameNode")]
  public partial class RegisterGameNode : global::ProtoBuf.IExtensible
  {
    public RegisterGameNode() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private string _ip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private proto_server.RegisterGameNode.Request _register_game_node = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"register_game_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.RegisterGameNode.Request register_game_node
    {
      get { return _register_game_node; }
      set { _register_game_node = value; }
    }
    private proto_server.CreateRemoteGame.Request _create_game_req = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"create_game_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.CreateRemoteGame.Request create_game_req
    {
      get { return _create_game_req; }
      set { _create_game_req = value; }
    }
    private proto_server.PlayersJoin.Request _players_join_req = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"players_join_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.PlayersJoin.Request players_join_req
    {
      get { return _players_join_req; }
      set { _players_join_req = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private proto_server.RegisterGameNode.Response _register_game_node = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"register_game_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.RegisterGameNode.Response register_game_node
    {
      get { return _register_game_node; }
      set { _register_game_node = value; }
    }
    private proto_server.CreateRemoteGame.Response _create_game_res = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"create_game_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.CreateRemoteGame.Response create_game_res
    {
      get { return _create_game_res; }
      set { _create_game_res = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRemoteGame")]
  public partial class CreateRemoteGame : global::ProtoBuf.IExtensible
  {
    public CreateRemoteGame() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private proto_game.GameMode _mode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.GameMode mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private proto_server.RegisterGameNode.Request _register_game_node = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"register_game_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.RegisterGameNode.Request register_game_node
    {
      get { return _register_game_node; }
      set { _register_game_node = value; }
    }
    private proto_server.CreateRemoteGame.Request _create_game_req = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"create_game_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.CreateRemoteGame.Request create_game_req
    {
      get { return _create_game_req; }
      set { _create_game_req = value; }
    }
    private proto_server.PlayersJoin.Request _players_join_req = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"players_join_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.PlayersJoin.Request players_join_req
    {
      get { return _players_join_req; }
      set { _players_join_req = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _max_players_allowed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"max_players_allowed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_players_allowed
    {
      get { return _max_players_allowed; }
      set { _max_players_allowed = value; }
    }
    private int _min_players_to_start;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"min_players_to_start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int min_players_to_start
    {
      get { return _min_players_to_start; }
      set { _min_players_to_start = value; }
    }
    private proto_server.RegisterGameNode.Response _register_game_node = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"register_game_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.RegisterGameNode.Response register_game_node
    {
      get { return _register_game_node; }
      set { _register_game_node = value; }
    }
    private proto_server.CreateRemoteGame.Response _create_game_res = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"create_game_res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.CreateRemoteGame.Response create_game_res
    {
      get { return _create_game_res; }
      set { _create_game_res = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayersJoin")]
  public partial class PlayersJoin : global::ProtoBuf.IExtensible
  {
    public PlayersJoin() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private readonly global::System.Collections.Generic.List<string> _players = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> players
    {
      get { return _players; }
    }
  
    private string _game_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private proto_server.RegisterGameNode.Request _register_game_node = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"register_game_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.RegisterGameNode.Request register_game_node
    {
      get { return _register_game_node; }
      set { _register_game_node = value; }
    }
    private proto_server.CreateRemoteGame.Request _create_game_req = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"create_game_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.CreateRemoteGame.Request create_game_req
    {
      get { return _create_game_req; }
      set { _create_game_req = value; }
    }
    private proto_server.PlayersJoin.Request _players_join_req = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"players_join_req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto_server.PlayersJoin.Request players_join_req
    {
      get { return _players_join_req; }
      set { _players_join_req = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameNodeStatus")]
  public partial class GameNodeStatus : global::ProtoBuf.IExtensible
  {
    public GameNodeStatus() {}
    
    private proto_server.FeedbackLevel _workload_level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"workload_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_server.FeedbackLevel workload_level
    {
      get { return _workload_level; }
      set { _workload_level = value; }
    }
    private int _players_connected;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"players_connected", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int players_connected
    {
      get { return _players_connected; }
      set { _players_connected = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStatusUpdate")]
  public partial class GameStatusUpdate : global::ProtoBuf.IExtensible
  {
    public GameStatusUpdate() {}
    
    private string _game_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private int _players_connected;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"players_connected", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int players_connected
    {
      get { return _players_connected; }
      set { _players_connected = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameFinished")]
  public partial class GameFinished : global::ProtoBuf.IExtensible
  {
    public GameFinished() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Commands")]
    public enum Commands
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER_GAME_NODE", Value=11)]
      REGISTER_GAME_NODE = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_REMOTE_GAME", Value=12)]
      CREATE_REMOTE_GAME = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYERS_JOIN", Value=13)]
      PLAYERS_JOIN = 13
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Events")]
    public enum Events
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NODE_STATUS", Value=11)]
      NODE_STATUS = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_FINISHED", Value=12)]
      GAME_FINISHED = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_STATUS_UPDATE", Value=13)]
      GAME_STATUS_UPDATE = 13
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FeedbackLevel")]
    public enum FeedbackLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Highest", Value=4)]
      Highest = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"High", Value=3)]
      High = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=2)]
      Normal = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Low", Value=1)]
      Low = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Lowest", Value=0)]
      Lowest = 0
    }
  
}