//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/game.proto
// Note: requires additional types generated from: ProtoFiles/common.proto
// Note: requires additional types generated from: ProtoFiles/profile.proto
namespace proto_game
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatValue")]
  public partial class StatValue : global::ProtoBuf.IExtensible
  {
    public StatValue() {}
    
    private proto_game.Stats _stat;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Stats stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
    private float _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float value
    {
      get { return _value; }
      set { _value = value; }
    }
    private float _step;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float step
    {
      get { return _step; }
      set { _step = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector")]
  public partial class Vector : global::ProtoBuf.IExtensible
  {
    public Vector() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DamageApply")]
  public partial class DamageApply : global::ProtoBuf.IExtensible
  {
    public DamageApply() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private int _bullet;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bullet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bullet
    {
      get { return _bullet; }
      set { _bullet = value; }
    }
    private int _attacker;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }
    private float _damage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _target;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ping")]
  public partial class Ping : global::ProtoBuf.IExtensible
  {
    public Ping() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private int _current_ping;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"current_ping", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int current_ping
    {
      get { return _current_ping; }
      set { _current_ping = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInput")]
  public partial class PlayerInput : global::ProtoBuf.IExtensible
  {
    public PlayerInput() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private float _force_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"force_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float force_x
    {
      get { return _force_x; }
      set { _force_x = value; }
    }
    private float _force_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"force_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float force_y
    {
      get { return _force_y; }
      set { _force_y = value; }
    }
    private float _rotation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private int _tick;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private bool _shoot = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"shoot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool shoot
    {
      get { return _shoot; }
      set { _shoot = value; }
    }
    private bool _skill = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool skill
    {
      get { return _skill; }
      set { _skill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _force_x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"force_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float force_x
    {
      get { return _force_x; }
      set { _force_x = value; }
    }
    private float _force_y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"force_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float force_y
    {
      get { return _force_y; }
      set { _force_y = value; }
    }
    private int _tick;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private bool _shoot;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"shoot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool shoot
    {
      get { return _shoot; }
      set { _shoot = value; }
    }
    private bool _skill;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool skill
    {
      get { return _skill; }
      set { _skill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FindRoom")]
  public partial class FindRoom : global::ProtoBuf.IExtensible
  {
    public FindRoom() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinGame")]
  public partial class JoinGame : global::ProtoBuf.IExtensible
  {
    public JoinGame() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private proto_profile.PlayerClasses _class;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_profile.PlayerClasses @class
    {
      get { return _class; }
      set { _class = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private int _map_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"map_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int map_id
    {
      get { return _map_id; }
      set { _map_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Contour")]
  public partial class Contour : global::ProtoBuf.IExtensible
  {
    public Contour() {}
    
    private readonly global::System.Collections.Generic.List<float> _x = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(1, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> x
    {
      get { return _x; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _y = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(2, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> y
    {
      get { return _y; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Map")]
  public partial class Map : global::ProtoBuf.IExtensible
  {
    public Map() {}
    
    private proto_game.Contour _border;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"border", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto_game.Contour border
    {
      get { return _border; }
      set { _border = value; }
    }
    private readonly global::System.Collections.Generic.List<proto_game.Contour> _obstacles = new global::System.Collections.Generic.List<proto_game.Contour>();
    [global::ProtoBuf.ProtoMember(2, Name=@"obstacles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto_game.Contour> obstacles
    {
      get { return _obstacles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DownloadMap")]
  public partial class DownloadMap : global::ProtoBuf.IExtensible
  {
    public DownloadMap() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private proto_game.Map _map;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"map", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto_game.Map map
    {
      get { return _map; }
      set { _map = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatUpgrade")]
  public partial class StatUpgrade : global::ProtoBuf.IExtensible
  {
    public StatUpgrade() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private proto_game.Stats _stat;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Stats stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerUpgrade")]
  public partial class PlayerUpgrade : global::ProtoBuf.IExtensible
  {
    public PlayerUpgrade() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncTick")]
  public partial class SyncTick : global::ProtoBuf.IExtensible
  {
    public SyncTick() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private int _tick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BulletAppeared")]
  public partial class BulletAppeared : global::ProtoBuf.IExtensible
  {
    public BulletAppeared() {}
    
    private int _tick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private float _direction;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MobAppeared")]
  public partial class MobAppeared : global::ProtoBuf.IExtensible
  {
    public MobAppeared() {}
    
    private proto_game.MobType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.MobType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<proto_game.StatValue> _stats = new global::System.Collections.Generic.List<proto_game.StatValue>();
    [global::ProtoBuf.ProtoMember(5, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto_game.StatValue> stats
    {
      get { return _stats; }
    }
  
    private float _hp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private float _attack_range;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"attack_range", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float attack_range
    {
      get { return _attack_range; }
      set { _attack_range = value; }
    }
    private proto_game.Weapons _weapon_used;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"weapon_used", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Weapons weapon_used
    {
      get { return _weapon_used; }
      set { _weapon_used = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PowerUpAppeared")]
  public partial class PowerUpAppeared : global::ProtoBuf.IExtensible
  {
    public PowerUpAppeared() {}
    
    private proto_game.PowerUpType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.PowerUpType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _lifetime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"lifetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lifetime
    {
      get { return _lifetime; }
      set { _lifetime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PowerUpGrabbed")]
  public partial class PowerUpGrabbed : global::ProtoBuf.IExtensible
  {
    public PowerUpGrabbed() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _who_grabbed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"who_grabbed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int who_grabbed
    {
      get { return _who_grabbed; }
      set { _who_grabbed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartGame")]
  public partial class StartGame : global::ProtoBuf.IExtensible
  {
    public StartGame() {}
    
    private int _tick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private int _time_left;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time_left", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time_left
    {
      get { return _time_left; }
      set { _time_left = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockAppeared")]
  public partial class BlockAppeared : global::ProtoBuf.IExtensible
  {
    public BlockAppeared() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private proto_game.Vector _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto_game.Vector position
    {
      get { return _position; }
      set { _position = value; }
    }
    private float _hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private proto_game.ExpBlocks _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.ExpBlocks type
    {
      get { return _type; }
      set { _type = value; }
    }
    private float _max_hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"max_hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float max_hp
    {
      get { return _max_hp; }
      set { _max_hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntityRemoved")]
  public partial class EntityRemoved : global::ProtoBuf.IExtensible
  {
    public EntityRemoved() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BulletsRemoved")]
  public partial class BulletsRemoved : global::ProtoBuf.IExtensible
  {
    public BulletsRemoved() {}
    
    private readonly global::System.Collections.Generic.List<int> _guid = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> guid
    {
      get { return _guid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnPickUp")]
  public partial class SpawnPickUp : global::ProtoBuf.IExtensible
  {
    public SpawnPickUp() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private proto_game.Pickups _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Pickups type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _guid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitState")]
  public partial class UnitState : global::ProtoBuf.IExtensible
  {
    public UnitState() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _rotation;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitStatesUpdate")]
  public partial class UnitStatesUpdate : global::ProtoBuf.IExtensible
  {
    public UnitStatesUpdate() {}
    
    private readonly global::System.Collections.Generic.List<proto_game.UnitState> _states = new global::System.Collections.Generic.List<proto_game.UnitState>();
    [global::ProtoBuf.ProtoMember(1, Name=@"states", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto_game.UnitState> states
    {
      get { return _states; }
    }
  
    private int _tick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeaveGame")]
  public partial class LeaveGame : global::ProtoBuf.IExtensible
  {
    public LeaveGame() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerExperience")]
  public partial class PlayerExperience : global::ProtoBuf.IExtensible
  {
    public PlayerExperience() {}
    
    private int _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerLevelUp")]
  public partial class PlayerLevelUp : global::ProtoBuf.IExtensible
  {
    public PlayerLevelUp() {}
    
    private int _lvl;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lvl
    {
      get { return _lvl; }
      set { _lvl = value; }
    }
    private int _expLeft;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"expLeft", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int expLeft
    {
      get { return _expLeft; }
      set { _expLeft = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerCoinsChange")]
  public partial class PlayerCoinsChange : global::ProtoBuf.IExtensible
  {
    public PlayerCoinsChange() {}
    
    private int _coins;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"coins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coins
    {
      get { return _coins; }
      set { _coins = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerStatusChange")]
  public partial class PlayerStatusChange : global::ProtoBuf.IExtensible
  {
    public PlayerStatusChange() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _hp = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncAttack")]
  public partial class SyncAttack : global::ProtoBuf.IExtensible
  {
    public SyncAttack() {}
    
    private int _sync_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sync_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sync_id
    {
      get { return _sync_id; }
      set { _sync_id = value; }
    }
    private int _first_bullet_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"first_bullet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int first_bullet_id
    {
      get { return _first_bullet_id; }
      set { _first_bullet_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnBullets")]
  public partial class SpawnBullets : global::ProtoBuf.IExtensible
  {
    public SpawnBullets() {}
    
    private float _direction;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private float _angleStep;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"angleStep", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float angleStep
    {
      get { return _angleStep; }
      set { _angleStep = value; }
    }
    private int _startId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"startId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startId
    {
      get { return _startId; }
      set { _startId = value; }
    }
    private float _damage;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _owner;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private proto_game.Bullets _type;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Bullets type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _tick;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitAttack")]
  public partial class UnitAttack : global::ProtoBuf.IExtensible
  {
    public UnitAttack() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _direction;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _time_advance;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"time_advance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time_advance
    {
      get { return _time_advance; }
      set { _time_advance = value; }
    }
    private int _first_bullet_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"first_bullet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int first_bullet_id
    {
      get { return _first_bullet_id; }
      set { _first_bullet_id = value; }
    }
    private int _tick;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerAppeared")]
  public partial class PlayerAppeared : global::ProtoBuf.IExtensible
  {
    public PlayerAppeared() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private proto_game.Vector _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public proto_game.Vector position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _guid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private readonly global::System.Collections.Generic.List<proto_game.StatValue> _stats = new global::System.Collections.Generic.List<proto_game.StatValue>();
    [global::ProtoBuf.ProtoMember(4, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto_game.StatValue> stats
    {
      get { return _stats; }
    }
  
    private float _hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private bool _local;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"local", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool local
    {
      get { return _local; }
      set { _local = value; }
    }
    private proto_profile.PlayerClasses _class;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_profile.PlayerClasses @class
    {
      get { return _class; }
      set { _class = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private proto_game.Skills _skill;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_game.Skills skill
    {
      get { return _skill; }
      set { _skill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScoreChanged")]
  public partial class ScoreChanged : global::ProtoBuf.IExtensible
  {
    public ScoreChanged() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameFinished")]
  public partial class GameFinished : global::ProtoBuf.IExtensible
  {
    public GameFinished() {}
    
    private int _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _coins;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"coins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coins
    {
      get { return _coins; }
      set { _coins = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DamageDone")]
  public partial class DamageDone : global::ProtoBuf.IExtensible
  {
    public DamageDone() {}
    
    private int _target;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private float _hp_left;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hp_left", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hp_left
    {
      get { return _hp_left; }
      set { _hp_left = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillCasted")]
  public partial class SkillCasted : global::ProtoBuf.IExtensible
  {
    public SkillCasted() {}
    
    private int _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private float _direction;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _tick;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private int _first_bullet_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"first_bullet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int first_bullet_id
    {
      get { return _first_bullet_id; }
      set { _first_bullet_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MobScriptType")]
    public enum MobScriptType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SimpleShooterMobScript", Value=1)]
      SimpleShooterMobScript = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SimpleBossScript", Value=2)]
      SimpleBossScript = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameMode")]
    public enum GameMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FFA", Value=1)]
      FFA = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamDeathmatch", Value=2)]
      TeamDeathmatch = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CaptureTheFlag", Value=3)]
      CaptureTheFlag = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Weapons")]
    public enum Weapons
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MachineGun", Value=1)]
      MachineGun = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DualMachineGun", Value=2)]
      DualMachineGun = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Canon", Value=3)]
      Canon = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MobGun", Value=4)]
      MobGun = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Pickups")]
    public enum Pickups
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SmallGoldCoin", Value=1)]
      SmallGoldCoin = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InvisibilityPickup", Value=2)]
      InvisibilityPickup = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RegenerationPickup", Value=3)]
      RegenerationPickup = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuadDamagePickup", Value=4)]
      QuadDamagePickup = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HugeBulletsPickUp", Value=5)]
      HugeBulletsPickUp = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeavyAmmo", Value=6)]
      HeavyAmmo = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Bullets")]
    public enum Bullets
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Common", Value=1)]
      Common = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CanonCore", Value=2)]
      CanonCore = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MonSlowBullet", Value=3)]
      MonSlowBullet = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SimpleBossProjectile1", Value=4)]
      SimpleBossProjectile1 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SimpleBoosProjectile2", Value=5)]
      SimpleBoosProjectile2 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SimpleBoosProjectile3", Value=6)]
      SimpleBoosProjectile3 = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MobType")]
    public enum MobType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Basic", Value=1)]
      Basic = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SimpleBoss", Value=2)]
      SimpleBoss = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PowerUpType")]
    public enum PowerUpType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DoubleDamage", Value=0)]
      DoubleDamage = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Invisibility", Value=1)]
      Invisibility = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WiderView", Value=2)]
      WiderView = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Regeneration", Value=3)]
      Regeneration = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BoosterType")]
    public enum BoosterType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefillHeavyAmmo", Value=1)]
      RefillHeavyAmmo = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RestoreFullHealth", Value=2)]
      RestoreFullHealth = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HealFollower", Value=3)]
      HealFollower = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AttackFollower", Value=4)]
      AttackFollower = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TrueSight", Value=5)]
      TrueSight = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Stats")]
    public enum Stats
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MaxHealth", Value=1)]
      MaxHealth = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HealthRegen", Value=2)]
      HealthRegen = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BulletDamage", Value=3)]
      BulletDamage = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillDamage", Value=4)]
      SkillDamage = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MovementSpeed", Value=5)]
      MovementSpeed = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReloadSpeed", Value=6)]
      ReloadSpeed = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Armor", Value=7)]
      Armor = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BulletSpeed", Value=8)]
      BulletSpeed = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillCooldown", Value=9)]
      SkillCooldown = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BulletSize", Value=10)]
      BulletSize = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Skills")]
    public enum Skills
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BigCannon", Value=1)]
      BigCannon = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ExpBlocks")]
    public enum ExpBlocks
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Small", Value=0)]
      Small = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Medium", Value=1)]
      Medium = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Big", Value=2)]
      Big = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Huge", Value=3)]
      Huge = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GoldBlock", Value=4)]
      GoldBlock = 4
    }
  
}