//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/profile.proto
// Note: requires additional types generated from: ProtoFiles/common.proto
namespace proto_profile
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClassInfo")]
  public partial class ClassInfo : global::ProtoBuf.IExtensible
  {
    public ClassInfo() {}
    
    private proto_profile.PlayerClasses _class;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto_profile.PlayerClasses @class
    {
      get { return _class; }
      set { _class = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private int _coins;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"coins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coins
    {
      get { return _coins; }
      set { _coins = value; }
    }
    private int _premium_coins;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"premium_coins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int premium_coins
    {
      get { return _premium_coins; }
      set { _premium_coins = value; }
    }
    private readonly global::System.Collections.Generic.List<proto_profile.ClassInfo> _classesInfo = new global::System.Collections.Generic.List<proto_profile.ClassInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"classesInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto_profile.ClassInfo> classesInfo
    {
      get { return _classesInfo; }
    }
  
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeNickname")]
  public partial class ChangeNickname : global::ProtoBuf.IExtensible
  {
    public ChangeNickname() {}
    
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private bool _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerClasses")]
    public enum PlayerClasses
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TypeA", Value=1)]
      TypeA = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TypeB", Value=2)]
      TypeB = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TypeC", Value=3)]
      TypeC = 3
    }
  
}